import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import StoreProvider from '@/components/reduxStore/storeProvider';
import BottomNavbar from '@/components/bottomNavbar/bottomNavbar';
import { NextProviders } from './nextuiProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`} >
        <NextProviders>
            <StoreProvider>
              <Header />
              {children}
              <Footer />
              <BottomNavbar />
            </StoreProvider>
        </NextProviders>
      </body>
    </html>
  );
}
